### ISSUE TITLE
[BUG] Provisioning Datasource does not work

### ISSUE THREAD

**Issue by ruddra** [hoptical/nodegraph-api-plugin#13]
**Describe the bug**
I tried to create provisioning datasource by following yml:

```
apiVersion: 1
 
datasources:
  - name: datasource
    type: hamedkarbasi93-nodegraphapi-datasource
    access: proxy
    url: http://localhost:8000/api/v1/predicted-data/poly-fit
```

It created a provisional datasource when I started the grafana, but when I try to use it, it throws error:

![image](https://user-images.githubusercontent.com/3099861/157994585-89e468f7-9917-40af-a13d-5d883581ab88.png)

**To Reproduce**
1. Create datasource.yml
2. Put it inside `/etc/grafana/provisioning/datasources`
3. Restart grafana and create a dashboard with Node graph and use the previous datasource.

**Expected behavior**
Should work.

**Screenshots**

**Desktop Information:**
 - OS: [e.g. Windows]
 - Browser [e.g. edge]
 - Plugin Version [e.g. latest]
 - Grafana Version [e.g. 8.4.1]

**Comment by hoptical** [comment]
@ruddra
Can you try again with _access_ in **direct** mode instead of _proxy_?

**Comment by ruddra** [comment]
Unfortunately direct did not work

**Comment by hoptical** [comment]
You have to use `baseUrl` instead of `url` in `jsonData` section:
```
apiVersion: 1
 
datasources:
  - name: nodegraph-provision
    type: hamedkarbasi93-nodegraphapi-datasource
    access: direct
    jsonData:
      baseUrl: http://localhost:5000
```
We will utilize `url` in the next release to make it compatible with the standard. But for now, you can use the above config.
